allowBuilds:
  dprint: true
  esbuild: true
  puppeteer: true
overrides:
  axios@>=1.0.0 <1.15.0: '>=1.15.0'
  basic-ftp@<=5.2.1: '>=5.2.2'
  basic-ftp@<=5.2.2: '>=5.3.0'
  basic-ftp@=5.2.0: '>=5.2.1'
  follow-redirects@<=1.15.11: '>=1.16.0'
