name: Bug Report
description: Create a report to help us improve.
labels: ["bug"]
title: "bug: "
type: Bug
body:
  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: The objects are not objecting 😔...
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: Running Version
      placeholder: What version are you running? ex. 3001.0.10/master
    validations:
      required: false

  - type: input
    attributes:
      label: Playground Link
      description: Link to the playground where the bug can be reproduced.
      placeholder: https://play.kaplayjs.com/...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Extra information
      description: Is there a method to reliably reproduce it? Did you expect something else to happen? Please add screenshots/evidence if possible.
      placeholder: So, i was kaplaying normally, then all of sudden...
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Summary
      options:
        - label: Fixed in v4000
        - label: Fixed in v3001
