// @ts-check

import fs from "fs";
import path from "path";
import puppeteer from "puppeteer";
import { serve } from "./dev/serve.ts";
import { build } from "./lib/build.ts";
import { wait } from "./lib/util.ts";

await build(true);

const server = serve();
const adress = server.address();
const port = typeof adress == "object" ? adress?.port : "unknown";

let failed = false;

console.log("launching browser");

const browser = await puppeteer.launch({
    args: ["--no-sandbox"],
});

console.log("testing...");

const examplesDir = fs.readdirSync("examples");
const examples = examplesDir.filter((p) => {
    const isExample = !p.startsWith(".") && p.endsWith(".js");
    if (!isExample) return false;

    const fileContent = fs.readFileSync(path.join("examples", p));
    const isTest = fileContent.includes("@test");
    return isTest;
}).map((d) => path.basename(d, ".js"));

const playtestsDir = fs.readdirSync("tests/playtests");
const playtests = playtestsDir.filter((p) => {
    const isPlaytest = !p.startsWith(".") && p.endsWith(".js");
    if (!isPlaytest) return false;

    const fileContent = fs.readFileSync(path.join("tests/playtests", p));
    const isTest = fileContent.includes("@test");
    return isTest;
}).map((d) => path.basename(d, ".js"));

for (const example of [...examples, ...playtests]) {
    console.log(`testing example "${example}"`);
    const page = await browser.newPage();
    page.on("pageerror", (err) => {
        if (err.message.startsWith("[rendering]")) return;
        failed = true;
        console.error(example, err);
    });
    page.on("error", (err) => {
        if (err.message.startsWith("[rendering]")) return;
        failed = true;
        console.error(example, err);
    });
    await page.goto(`http://localhost:${port}/${example}`);
    await page.addScriptTag({ path: "scripts/lib/autoinput.js" });
    // this is to allow video elements to play that need a "real" user input
    // instead of the fake clicks generated by the autoinput script.
    // KAPLAY will take the fake clicks, but the <video> elements are
    // controlled by the browser and need a real click.
    await page.click("canvas");
    await wait(20);
    await page.close();
}

browser.close();
server.close();

console.log(
    failed
        ? "One or more tests failed, all is kaboomed 💥"
        : "All tests have passed 🦖",
);

process.exit(failed ? 1 : 0);
