// @ts-check

import fs from "fs";
import path from "path";
import puppeteer from "puppeteer";
import { serve } from "./dev/serve.js";
import { build } from "./lib/build.js";
import { wait } from "./lib/util.js";

await build(true);
const port = process.env.PORT || 4000;
const server = serve({ port: port });

let failed = false;

console.log("launching browser");

const browser = await puppeteer.launch({
    args: ["--no-sandbox"],
});

console.log("testing...");

const examplesDir = fs.readdirSync("examples");
const examples = examplesDir.filter((p) => {
    const isExample = !p.startsWith(".") && p.endsWith(".js");
    if (!isExample) return false;

    const fileContent = fs.readFileSync(path.join("examples", p));
    const isTest = fileContent.includes("@test");
    return isTest;
}).map((d) => path.basename(d, ".js"));

for (const example of examples) {
    console.log(`testing example "${example}"`);
    const page = await browser.newPage();
    page.on("pageerror", (err) => {
        failed = true;
        console.error(example, err);
    });
    page.on("error", (err) => {
        failed = true;
        console.error(example, err);
    });
    await page.goto(`http://localhost:${port}/${example}`);
    await page.addScriptTag({ path: "scripts/lib/autoinput.js" });
    // this is to allow video elements to play that need a "real" user input
    // instead of the fake clicks generated by the autoinput script.
    // KAPLAY will take the fake clicks, but the <video> elements are
    // controlled by the browser and need a real click.
    await page.click("canvas");
    await wait(100);
    await page.close();
}

browser.close();
server.close();

console.log(
    failed
        ? "test suite failed, all is kaboomed"
        : "GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOD",
);
process.exit(failed ? 1 : 0);
