name: Publish to NPM

on:
  push:
    tags:
      - '4000*'
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: true
        default: "4000.0.0"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        run: npm publish --tag next